version: 2.1

orbs:
 android: circleci/android@0.2.1

jobs:
  build:
    executor: android/android
        
    steps:
      - checkout

      - run:
          name: Build
          command: ./gradlew build

      - run:
          name: Domain tests
          command: ./gradlew :domain:test

      - run:
          name: Android tests
          command: ./gradlew testDebugUnitTest
